# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
